/* eslint-disable max-len */
import { userInstance } from '../axios/axiosInstance';

export const userLogin = (values) => userInstance.post('/login', { ...values });
export const userSignup = (values) => userInstance.post('/register', { ...values });
export const verifyOtp = (otp) => userInstance.post('/verifyOtp', { otp });
export const userAuth = () => userInstance.get('/auth-user');
export const fetchGenreMovies = (genreName) => userInstance.get(`/movies/${genreName}`);
export const fetchMovie = (movieId) => userInstance.get(`/movies/view-movie/${movieId}`);
export const addRating = (value, movieId) => userInstance.get(`/content/add-rating/${movieId}?rating=${value}`);
export const addToWatchlist = (contentId, type) => userInstance.get(`/content/add-watchlist/${contentId}?type=${type}`);
export const fetchReview = (movieId) => userInstance.get(`/movies/view-movie/get-review/${movieId}`);
export const addReview = (contentId, review) => userInstance.post(`/content/add-review/${contentId}`, { review });
export const fetchActor = (actorId) => userInstance.get(`/movies/view-movie/actor/${actorId}`);
export const fetchCrew = (crewId) => userInstance.get(`/movies/view-movie/crew/${crewId}`);
export const fetchAllReviews = (contentId) => userInstance.get(`/content/reviews/${contentId}`);
export const fetchRelatedMovies = (movieId) => userInstance.get(`/movies/view-movie/related-movies/${movieId}`);
export const fetchGenreSeries = (genreName) => userInstance.get(`/series/${genreName}`);
export const fetchSeries = (showId) => userInstance.get(`/series/view-series/${showId}`);
export const fetchSeason = (seasonId) => userInstance.get(`/series/view-season/${seasonId}`);
export const fetchEpisode = (episodeId) => userInstance.get(`/series/view-episode/${episodeId}`);
export const fetchWatchlist = () => userInstance.get('/watchlist');
export const getUserDetails = () => userInstance.get('/profile');
export const updateUserDetails = (data) => userInstance.patch('/update-profile', { ...data });
export const updateUserAvatar = (formData) => userInstance.patch('/update-avatar', formData, { headers: { 'Content-Type': 'multipart/form-data' } });
// export const getFriend = (friendId) => userInstance.get(`/users?userId=${friendId}`);
export const fetchAllUsers = (query) => userInstance.get(`/users?search=${query}`);
export const friendRequest = (friendId) => userInstance.patch(`/add-friend?friendId=${friendId}`);
export const getChats = () => userInstance.get('/api/chat');
export const newChat = (friendId) => userInstance.post('/api/chat', { friendId });
export const newGroupChat = (obj) => userInstance.post('/api/chat/group', { ...obj });
export const chatRename = (obj) => userInstance.put('/api/chat/rename', { ...obj });
export const addToGroup = (obj) => userInstance.put('/api/chat/add', { ...obj });
export const removeFromGroup = (obj) => userInstance.put('/api/chat/remove', { ...obj });
export const chatMessages = (chatId) => userInstance.get(`/api/message/${chatId}`);
export const sendMsg = (obj) => userInstance.post('/api/message', { ...obj });
